version: '2'
services:
    amini-app:
        image: amini
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://amini-mysql:3306/amini?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    amini-mysql:
        extends:
            file: mysql.yml
            service: amini-mysql
